### PR TITLE
Add Looma inventory

### LINKED ISSUE #55: Add Looma data
Add phonological inventory data from the Woi-Bhalaga dialect of Loom (Guinean)

See: 45mishchenko.pdf

### PR DESCRIPTION
**Pull request by bnk7**
closes #55

### CODE REVIEW

**Comment by bnk7** [comment]
I didn't include the "strong"/"weak" initial consonant alternation because it seemed to have more to do with morphology and syntax than allophony. If you disagree, I would add a weak allophone to every consonant using the  ͉  lenition marker.

**Comment by drammock** [comment]
@bnk7 Before I review this one, let's get your local master branch back in shape so that you don't have to deal with old commits on every new pull request.

1. run `git fetch --all` to make sure your local machine knows the latest state of all the remote copies.
2. run `git checkout master` to make sure you're on your local master branch.

Now let's look at the last 15 commits on your *remote* master branch (since I can't see your *local* master branch):
```console
$ git checkout b_master  # b_master is my local name for your master branch
Switched to branch 'b_master'
Your branch is up to date with 'bnk7/master'.
$ git log --oneline -n 15
e1fab73 (HEAD -> b_master, bnk7/master) Merge branch 'master' of git://github.com/phoible/dev
a543488 (upstream/master, bambooforest/master, master) Add Abun inventory by Brynna (#286)
136a0d1 Merge branch 'master' of https://github.com/bnk7/dev
c866aa4 (origin/master, origin/HEAD) Mako inventory by Brynna (#283)
0940124 apply suggestions from code review
df3a760 re-add quotation marks
4ec1308 fix formatting 2
f98ee17 fix formatting
81d44ef Issue284 (#285)
7258c4a add Mako reference
c65715b add Mako
b261876 Issue265 (#281)
ca0af47 try to fix CIs (#279)
75319be Issue272 (#277)
b591a76 WIP: update / modernize some tests (#275)
```

These are sorted newest at the top, oldest at the bottom.  The first unwanted commit on this PR is c65715b ("add Mako"), so we want to rewind to one commit earlier than that (b261876).

```console
$ git reset --hard b261876
HEAD is now at b261876 Issue265 (#281)
```
Now we can fast-forward your local master to be fully in-sync with the upstream/master:

```console
$ git merge --ff-only upstream/master
Updating b261876..a543488
Fast-forward
 data/phoible-references.bib    |   17 ++
 raw-data/AA/README.md          |    4 +-
 raw-data/EA/README.md          |    4 +-
 raw-data/ER/README.md          |   11 +-
 raw-data/GM/README.md          |    4 +-
 raw-data/PH/README.md          |    6 +-
 raw-data/RA/README.md          |    4 +-
 raw-data/RA/Ramaswami1999.bib  | 1258 ----------------------------------------------------------------------------------------------------------
 raw-data/SAPHON/README.md      |    6 +-
 raw-data/SPA/README.md         |    4 +-
 raw-data/UPSID/README.md       |    6 +
 raw-data/UW/uw_inventories.tsv |   93 ++++++++
 raw-data/UZ/README.md          |    4 +-
 13 files changed, 147 insertions(+), 1274 deletions(-)
 delete mode 100644 raw-data/RA/Ramaswami1999.bib
 create mode 100644 raw-data/UW/uw_inventories.tsv
```

Notice that now the history on your master branch has changed:

```console
$ git log --oneline -n 10
a543488 (HEAD -> b_master, upstream/master, bambooforest/master, master) Add Abun inventory by Brynna (#286)
c866aa4 (origin/master, origin/HEAD) Mako inventory by Brynna (#283)
81d44ef Issue284 (#285)
b261876 Issue265 (#281)
ca0af47 try to fix CIs (#279)
75319be Issue272 (#277)
b591a76 WIP: update / modernize some tests (#275)
3a1d56f Issue276 (#278)
0905d28 fixes #271 -- todo: regen the data (#274)
c1a7e24 Ditch binary (#273)
```

Now we checkout the looma branch, and *rebase* it against your local master (rewind to the point where the histories are in sync, and then pick and choose which commits from `looma_branch` to add to the end of that history.

```console
$ git rebase --interactive master
```

This should open a text editor with the following:

```
pick c65715b add Mako
pick 7258c4a add Mako reference
pick f98ee17 fix formatting
pick 4ec1308 fix formatting 2
pick df3a760 re-add quotation marks
pick 0940124 apply suggestions from code review
pick d04ebd4 add Looma inventory
pick dd68a45 add Looma reference
pick e64aa96 fix tsv formatting

# instructions will appear here, I've omitted them for brevity
```

Change the first word of the first 6 rows from `pick` to `drop`, then save that file and exit. Voila!  Your local `master` branch and the `looma_branch` no longer have those redundant Mako commits:

```console
$ git log --oneline -n 10
2c9a5d3 (HEAD -> looma_branch) fix tsv formatting
745aa1d add Looma reference
93e1e07 add Looma inventory
a543488 (upstream/master, bambooforest/master, master, b_master) Add Abun inventory by Brynna (#286)
c866aa4 (origin/master, origin/HEAD) Mako inventory by Brynna (#283)
81d44ef Issue284 (#285)
b261876 Issue265 (#281)
ca0af47 try to fix CIs (#279)
75319be Issue272 (#277)
b591a76 WIP: update / modernize some tests (#275)
```

The last step is to force-push your local master to origin/master, and to force-push your local looma branch to `origin/looma_branch`.

```console
$ git push --force origin looma_branch
$ git checkout master
$ git push --force origin master
```

From this point forward, when you're ready to start work on a new inventory, do this:

```bash
git fetch --all
git checkout master
git merge --ff-only upstream/master
git checkout -b name_of_new_branch_goes_here
# make the changes, add, and commit them
# etc
```

**Comment by bnk7** [comment]
@drammock 
Thank you so much for the step by step instructions!

**Comment by drammock** [comment]
looks like it worked!  I only see the 3 looma-related commits in this PR now. @bambooforest can you review the phoneme inventory on this one?

**Comment by bambooforest** [comment]
@bnk7 @drammock -- inventory looks good. thanks!

**Pull request merged**
